name: Deploy to S3

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment
        run: |
          curl -X POST https://7fmprarasg.execute-api.us-west-1.amazonaws.com/prod
